### ISSUE TITLE
Error running ffmpeg

### ISSUE THREAD

**Issue by gotnull** [stilldavid/gopro-utils#2]
![screen shot 2017-03-31 at 9 40 03 am](https://cloud.githubusercontent.com/assets/578908/24529228/2d6e4d36-15f6-11e7-8a98-31bf5d95afb6.png)

Not sure why I receive:

Stream map '0:3' matches no streams.
To ignore this, add a trailing '?' to the map.

**Comment by stilldavid** [comment]
Can you provide the output from an `ffprobe filename.mp4` as well? It doesn't look like there is a data track in this file.

Are you using a Hero5 with GPS turned on?

**Comment by gotnull** [comment]
![screen shot 2017-03-31 at 9 46 39 am](https://cloud.githubusercontent.com/assets/578908/24529367/f8e28266-15f6-11e7-9230-53d1ee2386cb.png)

**Comment by stilldavid** [comment]
Yeah, it looks like it's only got video and audio - no data track :(

Is GPS turned on?

**Comment by gotnull** [comment]
I'll give it another shot with a proper video. Just thought I'd test it out 👍 

Thanks for the quick replies and of course the ability to extract the data!
