### ISSUE TITLE
'track' variable in json

### ISSUE THREAD

**Issue by patstar44** [stilldavid/gopro-utils#21]
Hi there,
firstly I want to thank you very much for this code. Saves me a lot of time!

Could you please explain to me what the variable 'track' in the json file from gopro2json exactly is?

Thank you very much,
Patrick

**Comment by stilldavid** [comment]
Hi there! The track is the path across the ground, derived from comparing locations over time. It might also be called "heading" but given the front of the camera might not be facing forward, I thought "track" was more accurate.
