### ISSUE TITLE
Errr

### ISSUE THREAD

**Issue by gotnull** [stilldavid/gopro-utils#3]
`» ./gopro2json -i ~/Desktop/GOPR0005.bin -o GOPR0005.json                                                            
zsh: permission denied: ./gopro2json`

**Comment by stilldavid** [comment]
Were you able to `go build` successfully?

Can you paste in the output from an `ls -al` in the `bin/gopro2json` directory just to make sure the perm bits are all set correctly.

**Comment by gotnull** [comment]
» /usr/local/go/bin/go build                                                                                         ◉ ◼◼◼◼◼◼◼◼◼◻
gopro2json.go:10:2: cannot find package "github.com/stilldavid/gopro-utils/telemetry" in any of:
	/usr/local/go/src/github.com/stilldavid/gopro-utils/telemetry (from $GOROOT)
	/Users/fulvio/go/src/github.com/stilldavid/gopro-utils/telemetry (from $GOPATH)

**Comment by gotnull** [comment]
» ls -al                                                                                                             ◉ ◼◼◼◼◼◼◼◼◼◻
total 8
drwxr-xr-x  3 fulvio  staff   102 31 Mar 09:43 .
drwxr-xr-x  5 fulvio  staff   170 31 Mar 09:45 ..
-rw-r--r--  1 fulvio  staff  1520 31 Mar 09:43 gopro2json.go

**Comment by stilldavid** [comment]
It looks like you might not have a `$GOPATH` set up - have you used go before?

I need to write up some docs about this, but you should be able to `go get github.com/stilldavid/gopro-utils`, then `cd` into it and `go get ./...` to get the dependencies.

The `$GOPATH` is pretty simple, you can [read about it here](https://github.com/golang/go/wiki/GOPATH).

**Comment by gotnull** [comment]
I can execute go from the path just fine.

When I run `go get github.com/stilldavid/gopro-utils` I get:

» go get github.com/stilldavid/gopro-utils                                                                           
can't load package: package github.com/stilldavid/gopro-utils: no buildable Go source files in /Users/fulvio/go/src/github.com/stilldavid/gopro-utils

**Comment by KonradIT** [comment]
@gotnull cd to your go directory, then go to src, make a folder called github.com and a folder called stilldavid inside it, then clone this repo in /stilldavid
