### ISSUE TITLE
Hero 7

### ISSUE THREAD

**Issue by dunha** [stilldavid/gopro-utils#31]
Thanks for the library

I had to add labels "UNIF" & "SROT" for the Hero 7
I haven't investigated what they are for, but my data requirement is very basic - just GPS.
Will look to ignore missing additional labels at some stage when I work out the best way to do it

Cheers

**Comment by phourglass** [comment]
Hello Dunha,

we need to purchase some gopros for an experiment where we reall need to output the metadata.
We would get Hero 7 if it works or older models if it does not.

At minimum, we need the GPS timestamps to synchronize with other systems at minimum.
Additionally, the gyro and accelerometers would be useful.

What can you read in your Hero 7 videos?
Do you have access to all outputs below? (and unif and srot are extra?).

Thanks for any info.
Philippe

~400 Hz 3-axis gyro readings
~200 Hz 3-axis accelerometer readings
~18 Hz GPS position (lat/lon/alt/spd)
1 Hz GPS timestamps
1 Hz GPS accuracy (cm) and fix (2d/3d)
1 Hz temperature of camera

**Comment by dunha** [comment]
Hi Philippe
You should be able to extract all the available metadata. I used code from https://github.com/JuanIrache/gopro-utils which combines this repository with others to extract the binary video stream and convert to csv depending on which sensor data is required.
The multiple sensor frequencies make it difficult to have one size fits all output.
I've modified the code for my purposes but GoPro seem to add fields for each model which need to be added or skipped.. It looks like these fields have been added in he master now so it should be fine with the 7. Just make sure you get the black hero version for the GPS
