### ISSUE TITLE
Add HiLight Tags

### ISSUE THREAD

**Issue by KonradIT** [stilldavid/gopro-utils#6]
Hi, I am trying to add a hilight tag write out to the program, [here is my progress](https://github.com/KonradIT/gopro-utils/commit/caf8c2671949b0da0a460d84c1f40ad43fb0a7f6). Hilight tags are time (in milliseconds) pinpoints in the video. I do not have a HERO5 to test the integration, I found [this repo](https://github.com/iNViTiON/GoPro-Tagging) which reads HiLight tags and works with my HERO4 Black footage. To tag a new hilight tag press the side button during a recording or use the GoPro App.

**Comment by KonradIT** [comment]
Doesn't seem that the 0:3 stream stores HMMT though, at least not in HERO4 Black.

This is what's on 0:3 : 

```
GPRO
HD4.02.05.00.00LAT4112400326634
Q&1a0
HERO4 Black
Q&1a0
```

`LAT4112400326634` does not seem to be a guess (?)

**Comment by JuanIrache** [comment]
Hi Konrad, Here's a H5Session clip with a Highlight tag for you to test https://www.dropbox.com/s/qqficevgrjlrz7x/GOPR0077.MP4?dl=0

**Comment by KonradIT** [comment]
@JuanIrache nice, btw on my repo I managed to do [this[(https://streamable.com/6uvy1)

**Comment by KonradIT** [comment]
HMMT appears to be on some other channel other than GPMD, closing this.

**Comment by stilldavid** [comment]
Someday I'd like to re-open this!

HiLight tags are in the `mp4` header, not embedded in the metadata stream. It would involve parsing the file a bit more than this code does, but it would fall in the realm of what should be possible in this repo.

From what I understand, we should look in the `udta` atom in the `moov` header, but this stuff goes over my head pretty quick until I dive in to the `mp4 container format.

**Comment by KonradIT** [comment]
@stilldavid yes it's in MOOV stream.
